app/models/document.py
import datetime

from sqlalchemy import Column, Integer, String, DateTime, Text, Table, ForeignKey
from sqlalchemy.orm import backref, relationship

from flask import current_app

from app import db


class Document(db.Model):

    __tablename__ = 'documents'

    id = Column(Integer, primary_key=True)
    title = Column(String(500))
    original_file_name = Column(String(500))
    uploaded_file_name = Column(String(500))
    body = Column(Text)
    uploaded_user = Column(Integer, ForeignKey('users.id'), nullable=True)
    created_at = Column(DateTime, default=datetime.datetime.utcnow())
    updated_at = Column(DateTime, on_delete=datetime.datetime.utcnow())

    def __str__(self):
        return '<Document {}>'.format(self.name)
    
    @property
    def tag_list(self):
        list_tag_document = ', '.join(str(i.tag.name) for i in self.document_tags)
        return list_tag_document
    
    @staticmethod
    def get_document_info(document_id):
        document_info = (
            db.session.query(Document)
            .filter(Document.id == document_id)
            .first()
        )
        if not document_info:
            return {}
        return document_info
    
    @property
    def path_file(self):
        return '{}/{}'.format(current_app.config['PATH_UPLOAD'], self.uploaded_file_name)


class Tag(db.Model):

    __tablename__ = 'tags'

    id = Column(Integer, primary_key=True)
    name = Column(String(255))
    created_at = Column(DateTime, default=datetime.datetime.utcnow())

    def __str__(self):
        return '<Tag {}>'.format(self.name)
    
    @staticmethod
    def count():
        return db.session.query(Tag).count()

class DocumentTag(db.Model):

    __tablename__ = 'document_tags'

    id = Column(Integer, primary_key=True)
    id_document = Column(Integer, ForeignKey('documents.id'))
    id_tag = Column(Integer, ForeignKey('tags.id'))
    
    document = relationship(Document, backref=backref("document_tags", cascade="all, delete-orphan"))
    tag = relationship(Tag, backref=backref("document_tags", cascade="all, delete-orphan"))

    def __str__(self):
        return '<DocumentTag {} {}>'.format(self.id_document, self.id_tag)


class RequestDocumentPermission(db.Model):

    __tablename__ = 'request_document_permission'

    id = Column(Integer, primary_key=True)
    id_document = Column(Integer, ForeignKey('documents.id'))
    id_user = Column(Integer, ForeignKey('users.id'))
    status = Column(Integer) # 0 = request; 1 = granted; 3 = denied
    reason = Column(String(500))
    created_at = Column(DateTime, default=datetime.datetime.utcnow())
    updated_at = Column(DateTime, on_update=datetime.datetime.utcnow())

    document = relationship(Document, backref=backref("request_document_permission", cascade="all, delete-orphan"))

    @property
    def user(self):
        from app.models.authentication import User
        return db.session.query(User).filter(User.id == self.id_user).first()

app/document/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileRequired
from wtforms import StringField, SelectMultipleField, SelectField, TextAreaField
from wtforms.fields.core import SelectField
from wtforms.validators import DataRequired

from app import db
from app.models.document import Tag


class DocumentForm(FlaskForm):
    title = StringField(validators=[DataRequired()])
    uploaded_file = FileField(validators=[FileRequired()])
    tags = SelectMultipleField(
        'Tags',
        validators=[DataRequired()],
        coerce=int
    )


class DocumentEditForm(FlaskForm):
    title = StringField(validators=[DataRequired()])
    uploaded_file = FileField()
    tags = SelectMultipleField(
        'Tags',
        validators=[DataRequired()],
        coerce=int
    )


class TagForm(FlaskForm):
    name = StringField(validators=[DataRequired()])


class RequestPermissionDocumentForm(FlaskForm):
    documents = SelectField(
        'Document',
        validators=[DataRequired()],
        render_kw={
            'class': 'form-control select2-document',
        },
        coerce=int
    )
    reason = TextAreaField(
        'Reason', 
        validators=[DataRequired()],
        render_kw={
            'class': 'form-control'
        }
    )

app/document/__init__.py
from flask import Blueprint

document_blueprint = Blueprint('document_blueprint', __name__, url_prefix='/document')

from .views import *

app/document/views.py
import datetime
import os
import uuid

from flask import request, render_template, current_app, redirect, url_for, abort
from werkzeug.utils import secure_filename
from flask_login import current_user, login_required
from sqlalchemy import or_, and_

from app import db
from app import document
from app.models.document import Document, Tag, DocumentTag, RequestDocumentPermission
from app.models.authentication import UserPermissionDocument, UserPermissionTag
from app.document import document_blueprint as dp
from app.document.forms import DocumentForm, TagForm, DocumentEditForm, RequestPermissionDocumentForm
from app.utils.pdf_util import convert_pdf_to_text
from app.utils.elasticsearch_util import add_document_to_index
from app.utils.logging_util import default_logger


@dp.route('/')
def index():
    return render_template('layout.html')


@dp.route('/index', methods=['GET'])
@login_required
def index_document():
    logger = default_logger(__name__)
    page = request.args.get('page', 1, type=int)
    if current_user.role == 0:
        documents = db.session.query(Document).paginate(page, current_app.config['POST_PER_PAGE'], False)
    else:
        user_id = current_user.id
        user_permission_documents = db.session.query(UserPermissionDocument.id_document).filter(UserPermissionDocument.id_user == user_id).subquery()
        user_permission_tag = db.session.query(UserPermissionTag.id_tag).filter(UserPermissionTag.id_user == user_id).subquery()
        document_permission_tag = db.session.query(DocumentTag.id_document).filter(DocumentTag.id_tag.in_(user_permission_tag)).subquery()
        documents = db.session.query(Document).filter(or_(
            Document.id.in_(user_permission_documents),
            Document.id.in_(document_permission_tag),
            Document.uploaded_user == user_id)
        ).paginate(page, current_app.config['POST_PER_PAGE'], False)

    next_url = url_for('document_blueprint.index_document', page=documents.next_num) if documents.has_next else None
    prev_url = url_for('document_blueprint.index_document', page=documents.prev_num) if documents.has_prev else None

    return render_template('document/index.html', documents=documents.items, next_url=next_url, prev_url=prev_url)


@dp.route('/create', methods=['GET', 'POST'])
@login_required
def create_document():
    logger = default_logger(__name__)
    form = DocumentForm()
    tag_query = db.session.query(Tag).all()
    choices = [(int(tag.id), tag.name) for tag in tag_query]
    form.tags.choices = choices
    if form.validate_on_submit():
        file_pdf = form.uploaded_file.data
        title_pdf = form.title.data
        original_file_name = secure_filename(file_pdf.filename)
        uploaded_file_name = '{}.pdf'.format(str(uuid.uuid4()))
        tags = form.tags.data
        user_id = current_user.get_id()

        file_pdf.save(
            os.path.join(
                current_app.config['PATH_UPLOAD'], 'pdf', uploaded_file_name
            )
        )
        logger.info("Success upload document {} to {}".format(uploaded_file_name, current_app.config['PATH_UPLOAD']))

        # save to db
        document = Document()
        document.title = title_pdf
        document.original_file_name = original_file_name
        document.uploaded_file_name = uploaded_file_name
        document.body = ''
        document.uploaded_user = user_id
        db.session.add(document)
        db.session.commit()

        for tag in tags:
            dc = DocumentTag(
                id_document=document.id,
                id_tag=tag
            )
            db.session.add(dc)

        db.session.commit()
        return redirect(url_for('document_blueprint.index_document'))
    return render_template('document/create.html', form=form)


@dp.route('/edit/<int:document_id>', methods=['GET', 'POST'])
@login_required
def edit_document(document_id):
    logger = default_logger(__name__)
    document = db.session.query(Document).filter(Document.id == document_id).first()
    document_tags = [i.tag.id for i in document.document_tags]
    form = DocumentEditForm(obj=document)
    tag_query = db.session.query(Tag).all()
    choices = [(int(tag.id), tag.name) for tag in tag_query]
    form.tags.choices = choices
    form.tags.data = document_tags
    form.uploaded_file.data = document.path_file
    if form.validate_on_submit():
        if not form.uploaded_file:
            file_pdf = form.uploaded_file.data
            original_file_name = secure_filename(file_pdf.filename)
            uploaded_file_name = '{}.pdf'.format(str(uuid.uuid4()))
            document.original_file_name = original_file_name
            document.uploaded_file_name = uploaded_file_name
            file_pdf.save(
                os.path.join(
                    current_app.config['PATH_UPLOAD'], 'pdf', uploaded_file_name
                )
            )
            logger.info("Success upload document {} to {}".format(uploaded_file_name, current_app.config['PATH_UPLOAD']))
        title_pdf = form.title.data
        tags = form.tags.data

        document.title = title_pdf
        document.body = ''

        db.session.query(DocumentTag).filter(DocumentTag.id_document == document.id).delete()
        db.session.commit()

        for tag in tags:
            dc = DocumentTag(
                id_document=document.id,
                id_tag=tag
            )
            db.session.add(dc)
        db.session.commit()
        return redirect(url_for('document_blueprint.detail_document', document_id=document.id))
    return render_template('document/edit.html', form=form)


@dp.route('/detail/<int:document_id>', methods=['GET'])
@login_required
def detail_document(document_id):
    document = db.session.query(Document).filter(Document.id == document_id).first()
    return render_template('document/detail.html', document=document)


@dp.route('/permission/index')
@login_required
def index_list_permission():
    logger = default_logger(__name__)
    user_id = current_user.get_id()
    page = request.args.get('page', 1, type=int)
    list_permission = db.session.query(RequestDocumentPermission).filter(RequestDocumentPermission.id_user == user_id).paginate(page, current_app.config['POST_PER_PAGE'], False)
    next_url = url_for('document_blueprint.index_admin_permission_document', page=list_permission.next_num) if list_permission.has_next else None
    prev_url = url_for('document_blueprint.index_admin_permission_document', page=list_permission.prev_num) if list_permission.has_prev else None
    return render_template('/document/index_list_permission.html', permissions=list_permission.items, next_url=next_url, prev_url=prev_url)


@dp.route('/request_permission', methods=['GET', 'POST'])
@login_required
def request_permission_document():
    logger = default_logger(__name__)
    form = RequestPermissionDocumentForm()
    user_id = current_user.get_id()
    user_have_permission = db.session.query(UserPermissionDocument.id_document).filter(UserPermissionDocument.id_user == user_id).subquery()
    user_permission_tag = db.session.query(UserPermissionTag.id_tag).filter(UserPermissionTag.id_user == user_id).subquery()
    document_permission_tag = db.session.query(DocumentTag.id_document).filter(DocumentTag.id_tag.in_(user_permission_tag)).subquery()
    document_query = db.session.query(
        Document
    ).filter(and_(
            ~Document.id.in_(user_have_permission),
            ~Document.id.in_(document_permission_tag),
            Document.uploaded_user != user_id)
    ).all()
    document_choices = [(int(document.id), document.title) for document in document_query]
    form.documents.choices = document_choices
    if form.validate_on_submit():
        user_id = current_user.get_id()
        document_id = form.documents.data
        reason = form.reason.data

        rpd = RequestDocumentPermission(
            id_user = user_id,
            id_document = document_id,
            reason = reason,
            status = 0
        )
        db.session.add(rpd)
        db.session.commit()

        logger.info('Success request the permission')
        return redirect(url_for('document_blueprint.index_document'))
    return render_template('document/request_permission.html', form=form)


@dp.route('/permission/index/admin')
@login_required
def index_admin_permission_document():
    logger = default_logger(__name__)
    page = request.args.get('page', 1, type=int)
    list_permission = db.session.query(RequestDocumentPermission).paginate(page, current_app.config['POST_PER_PAGE'], False)
    next_url = url_for('document_blueprint.index_admin_permission_document', page=list_permission.next_num) if list_permission.has_next else None
    prev_url = url_for('document_blueprint.index_admin_permission_document', page=list_permission.prev_num) if list_permission.has_prev else None
    return render_template('/permission/request/index.html', permissions=list_permission.items, next_url=next_url, prev_url=prev_url)


@dp.route('/permission/response/admin', methods=['POST'])
@login_required
def response_permission():
    logger = default_logger(__name__)
    id_request_permission = int(request.form['id_request_permission'])
    id_status = int(request.form['id_status'])
    id_user = int(request.form['id_user'])
    id_document = int(request.form['id_document'])
    request_permission = db.session.query(RequestDocumentPermission).filter(RequestDocumentPermission.id == id_request_permission).first()
    request_permission.status = id_status
    if id_status == 1:
        upd = UserPermissionDocument(
            id_user = id_user,
            id_document = id_document
        )
        db.session.add(upd)
    request_permission.updated_at = datetime.datetime.now()
    db.session.commit()
    return redirect(url_for('document_blueprint.index_admin_permission_document'))



@dp.route('/tag/index', methods=['GET'])
@login_required
def index_tag():
    logger = default_logger(__name__)

app/templates/document/create.html
{% extends "layout.html" %}

{% block title %}
Upload Document
{% endblock title %}

{% block content %}
    <div class="card">
        <div class="card-body">
            <h5>Upload Documents</h5>
            <br>
            <div class="container-fluid">
            <form action="" method="POST" enctype="multipart/form-data">
                {{ form.csrf_token }}
                <div class="form-group row">
                    <label for="titleDocument">Title</label>
                    <div class="col-sm-10">
                        {{ form.title(class_="form-control")}}
                    </div>
                </div>
                <div class="form-group row">
                    <label for="Tags">Tags</label>
                    <div class="col-sm-10">
                        {{ form.tags(class_="form-control select2-tags")}}
                    </div>
                </div>
                <div class="form-group row">
                    <label for="fileDocument">File</label>
                    <div class="col-sm-10">
                        {{ form.uploaded_file(class_="form-control-fileclear")}}
                    </div>
                </div>
                <p>
                    {% if form.errors %}
                        {{ form.errors }}
                    {% endif %}
                </p>

                <button type="submit" class="btn btn-primary">Save</button>
            </form>
        </div>
    </div>
{% endblock content %}

{% block script %}
<script>
    $(document).ready(function() {
        $('.select2-tags').select2();
    });
</script>
{% endblock script %}

app/templates/document/detail.html
{% extends "layout.html" %}

{% block title %}
Detail Document
{% endblock title %}

{% block content %}
<div class="card">
    <div class="card-body">
        <h5>Detail Document</h5>
        <div class="container-fluid">
            <table class="table">
                <tr>
                    <td>Title</td>
                    <td>{{ document.title }}</td>
                </tr>
                <tr>
                    <td>Original File Name</td>
                    <td>{{ document.original_file_name }}</td>
                </tr>
                <tr>
                    <td>Tag</td>
                    <td>{{ document.tag_list }}</td>
                </tr>
                <tr>
                    <td>Uploaded Date</td>
                    <td>{{ document.created_at }}</td>
                </tr>
            </table>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-sm-12">
        <object data="{{ url_for('static', filename='uploaded_dev/pdf/' + document.uploaded_file_name) }}" type="application/pdf" width="100%" height="1000px">
            <iframe src="{{ url_for('static', filename='uploaded_dev/pdf/' + document.uploaded_file_name) }} }}"></iframe>
        </object>
    </div>
</div>
{% endblock content %}

app/templates/document/edit.html
{% extends "layout.html" %}

{% block title %}
Edit Document
{% endblock title %}

{% block content %}
    <div class="card">
        <div class="card-body">
            <h5 class="card-body">Edit Documents</h5>
            <div class="container-fluid">
            <form action="" method="POST" enctype="multipart/form-data">
                {{ form.csrf_token }}
                <div class="form-group row">
                    <label for="titleDocument">Title</label>
                    <div class="col-sm-10">
                        {{ form.title(class_="form-control")}}
                    </div>
                </div>
                <div class="form-group row">
                    <label for="Tags">Tags</label>
                    <div class="col-sm-10">
                        {{ form.tags(class_="form-control select2-tags")}}
                    </div>
                </div>
                <div class="form-group row">
                    <label for="fileDocument">File</label>
                    <div class="col-sm-10">
                        {{ form.uploaded_file(class_="form-control-fileclear")}}
                    </div>
                </div>
                <p>
                    {% if form.errors %}
                        {{ form.errors }}
                    {% endif %}
                </p>

                <button type="submit" class="btn btn-primary">Save</button>
            </form>
        </div>
    </div>
{% endblock content %}

{% block script %}
<script>
    $(document).ready(function() {
        $('.select2-tags').select2();
    });
</script>
{% endblock script %}

app/templates/document/index.html
{% extends "layout.html" %}

{% block title %}
Index Document
{% endblock title %}

{% block content %}

<div class="card">
    <div class="card-body container-fluid">
        <h5>Index Documents</h5>
        <br>
        <div class="row">
            <div class="col-sm-6">
                <a class="btn btn-primary" href="{{ url_for('document_blueprint.create_document') }}">Upload Document</a>
            </div>
            {% if current_user.role != 0 %}
                <div class="col-sm-6" align="right">
                    <a class="btn btn-primary" href="{{ url_for('document_blueprint.request_permission_document') }}">Request Permission</a>
                </div>
            {% endif %}
        </div> 
        <br>
        <div class="container-fluid">
            <table class="table">
                <thead class="thead-dark">
                    <tr>    
                        <th>No.</th>
                        <th>Title</th>
                        <th>Original File Name</th>
                        <th>Tag</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for document in documents %}
                        <tr>
                            <th scope="row">{{ loop.index }}</th>
                            <td>{{ document.title }}</td>
                            <td>{{ document.original_file_name }}</td>
                            <td>{{ document.tag_list }}</td>
                            <td>
                                <div class="col-sm-12">
                                    <div class="row">
                                        <div class="col-sm-6">
                                            <a href="{{ url_for('document_blueprint.edit_document', document_id=document.id) }}"><button class="btn btn-secondary">Edit</button></a>
                                        </div>
                                        <div class="col-sm-6">
                                            <a href="{{ url_for('document_blueprint.detail_document', document_id=document.id) }}"><button class="btn btn-secondary">Detail</button></a>
                                        </div>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% if prev_url %}
                <a href="{{ prev_url }}">Previous Page</a>
            {% endif %}
            {% if next_url %}
                <a href="{{ next_url }}">Next Page</a>
            {% endif %}
        </div>
    </div>
</div>
{% endblock content %}

app/templates/document/index_list_permission.html
{% extends "layout.html" %}

{% block title %}
Index Permission Document
{% endblock title %}

{% block content %}

<div class="card">
    <div class="card-body container-fluid">
        <h5>Index Requested Permission</h5>
        <br>
        <div class="row">
            <div class="col-sm-6">
                <a class="btn btn-primary" href="{{ url_for('document_blueprint.request_permission_document') }}">Request Permission</a>
            </div>
        </div> 
        <br>
        <div class="container-fluid">
            <table class="table">
                <thead class="thead-dark">
                    <tr>    
                        <th>No.</th>
                        <th>Title</th>
                        <th>Reason</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>
                    {% for permission in permissions %}
                        <tr>
                            <th scope="row">{{ loop.index }}</th>
                            <td>{{ permission.document.title }}</td>
                            <td>{{ permission.reason }}</td>
                            {% if permission.status == 0 %}
                                <td>Pending</td>
                            {% elif permission.status == 1 %}
                                <td>Granted</td>
                            {% else %}
                                <td>Rejected</td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% if prev_url %}
                <a href="{{ prev_url }}">Previous Page</a>
            {% endif %}
            {% if next_url %}
                <a href="{{ next_url }}">Next Page</a>
            {% endif %}
        </div>
    </div>
</div>
{% endblock content %}

app/templates/document/request_permission.html
{% extends "layout.html" %}

{% block title %}
Request Permission Document
{% endblock title %}

{% block content %}
    <div class="card">
        <div class="card-body">
            <h5>Request Permission Document</h5>
            <br>
            <div class="container-fluid">
                <form action="" method="POST" enctype="multipart/form-data">
                    {{ form.csrf_token }}
                    <div class="form-group row">
                        <label for="Document">Document</label>
                        <div class="col-sm-10">
                            {{ form.documents }}
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="Reason">Reason</label>
                        <div class="col-sm-10">
                            {{ form.reason }}
                        </div>
                    </div>
                    <p>
                        {% if form.errors %}
                            {{ form.errors }}
                        {% endif %}
                    </p>

                    <button type="submit" class="btn btn-primary">Save</button>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

{% block script %}
<script>
    $(document).ready(function() {
        $('.select2-document').select2();
    });
</script>
{% endblock script %}

app/templates/document/upload.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Upload File PDF</title>
</head>
<body>
    <form method="POST" enctype="multipart/form-data">
        {{ form.csrf_token }}
        {{ form.uploaded_file }}
        <input type="submit" class="btn btn-primary" value="Submit">
    </form>
</body>
</html>